name: Build .deb file

on:
  push:
    tags:
      - "v*" # Triggers on pushes to tags starting with "v"

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name and remove 'v'
        id: get_version
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION="${TAG_NAME#v}" # Removes a leading 'v' if present
          echo "Original Tag Name: $TAG_NAME"
          echo "Version (without 'v'): $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV # Make VERSION available to subsequent steps

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "REPO"
     
      - name: Copy files to keep extraneous files out of the package, then build the package
        run: |
          mkdir PKG_SOURCE
          cp -Rf REPO/usr REPO/DEBIAN PKG_SOURCE
          dpkg-deb --build PKG_SOURCE proxmox-sdn-vlan-qos_${{ env.VERSION }}_all.deb
        
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: proxmox-sdn-vlan-qos_${{ env.VERSION }}_all.deb
